### ISSUE TITLE
Old Arenas are not removed

### ISSUE THREAD

**Issue by Kruize1** [teozfrank/DuelMe#72]
I setup 2 arenas. I removed the old one, but it keeps coming back after I reboot my server.

Even if I edit the .yml file manually, or use the command , the arena always comes back.

**Comment by teozfrank** [comment]
How did you remove it? One way that will work is **stop** your server not restart, and delete the arenas.yml or remove whatever arena you want and then start the server. You see the plugin caches the arenas when it enables then saves from the cache to disk when the plugin gets disabled. That's why they keep coming back you are not meant to manually edit them.

**Comment by Kruize1** [comment]
I'll try these steps when I get home.

1. Remove the arena via the in-game command
2. Stop the server.
3. Delete the .yml file 
4. Start the server
5. See if it comes back

**Comment by Kruize1** [comment]
These steps worked! I'll close this issue.

**Comment by teozfrank** [comment]
Fixed in latest update.
